version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-api-app
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port
      8000"
    environment:
      DB_HOST: db
      DB_PORT: '5432'
      DB_NAME: filmesdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
    - 8000:8000
    depends_on:
    - db
    networks:
    - filme-network
  db:
    image: postgres:13
    container_name: movie-db
    environment:
      POSTGRES_DB: filmesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - filme-network
volumes:
  postgres_data: {}
networks:
  filme-network:
    external: true
